FROM clojure:lein-2.7.1-alpine
MAINTAINER Sarah Roberts <sarahr@cyverse.org>
ARG git_commit=unknown
LABEL org.iplantc.de.grouper.git-ref="$git_commit"

RUN apk add --no-cache git

ENV CONSUL_TEMPLATE_BASE=https://releases.hashicorp.com/consul-template
ENV CONSUL_TEMPLATE_VERSION=0.16.0
ENV CONSUL_TEMPLATE_SHA256SUM=064b0b492bb7ca3663811d297436a4bbf3226de706d2b76adade7021cd22e156
ENV CONSUL_TEMPLATE_FILE=consul-template_${CONSUL_TEMPLATE_VERSION}_linux_amd64.zip

ADD ${CONSUL_TEMPLATE_BASE}/${CONSUL_TEMPLATE_VERSION}/${CONSUL_TEMPLATE_FILE} .

RUN echo "${CONSUL_TEMPLATE_SHA256SUM}  ${CONSUL_TEMPLATE_FILE}" | sha256sum -c - \
    && unzip ${CONSUL_TEMPLATE_FILE} \
    && mkdir -p /usr/local/bin \
    && mv consul-template /usr/local/bin/consul-template

# Copy the configuration files to temporary locations.
COPY configs /tmp/configs

# Grouper environment variables.
ENV GROUPER_VERSION 2.3.0
ENV GROUPER_BASE_URL http://software.internet2.edu/grouper/release/$GROUPER_VERSION
ENV GROUPER_API_TGZ grouper.apiBinary-$GROUPER_VERSION.tar.gz
ENV GROUPER_UI_TGZ grouper.ui-$GROUPER_VERSION.tar.gz
ENV GROUPER_WS_TGZ grouper.ws-$GROUPER_VERSION.tar.gz
ENV GROUPER_INS_JAR grouperInstaller.jar
ENV GROUPER_BASE /opt/grouper
ENV GROUPER_LOGS /var/log/grouper
ENV GROUPER_CONF /etc/grouper
ENV GROUPER_TEMP /tmp/grouper
ENV GROUPER_HOME $GROUPER_BASE/api
ENV GROUPER_UI_HOME $GROUPER_BASE/ui
ENV GROUPER_WS_HOME $GROUPER_BASE/ws
ENV PATH $GROUPER_HOME/bin:$PATH

# Web application environment variables.
ENV WEBAPPS_HOME /usr/src/app

# Environment vairables for Bouncy Castle
ENV BCPROV_BASE http://bouncycastle.org/download
ENV BCPROV_JAR bcprov-jdk15on-156.jar

COPY install-utils.sh /tmp/install-utils.sh
COPY install-grouper.sh /tmp/install-grouper.sh
RUN mkdir -p $WEBAPPS_HOME \
    && /tmp/install-grouper.sh \
    && rm /tmp/install-grouper.sh /tmp/install-utils.sh

COPY consul.hcl $WEBAPPS_HOME/consul.hcl
COPY templates $WEBAPPS_HOME/templates
COPY generate-configs.sh /usr/bin/generate-configs.sh

WORKDIR $WEBAPPS_HOME
