FROM discoenv/war-runner
MAINTAINER Dennis Roberts <dennis@cyverse.org>
ARG git_commit=unknown
LABEL org.iplantc.de.grouper.git-ref="$git_commit"

# Copy the configuration files to temporary locations.
COPY configs /tmp/configs

# Environment variables for ant.
ENV ANT_HOME /opt/apache-ant
ENV PATH $PATH:$ANT_HOME/bin
ENV ANT_BASE https://www.apache.org/dist/ant/binaries
ENV ANT_VERSION 1.9.9
ENV ANT_URL $ANT_BASE/apache-ant-$ANT_VERSION-bin.tar.gz

# Grouper environment variables.
ENV GROUPER_VERSION 2.3.0
ENV GROUPER_BASE_URL http://software.internet2.edu/grouper/release/$GROUPER_VERSION
ENV GROUPER_API_TGZ grouper.apiBinary-$GROUPER_VERSION.tar.gz
ENV GROUPER_UI_TGZ grouper.ui-$GROUPER_VERSION.tar.gz
ENV GROUPER_WS_TGZ grouper.ws-$GROUPER_VERSION.tar.gz
ENV GROUPER_INS_JAR grouperInstaller.jar
ENV GROUPER_BASE /opt/grouper
ENV GROUPER_LOGS /var/log/grouper
ENV GROUPER_CONF /etc/grouper
ENV GROUPER_TEMP /tmp/grouper
ENV GROUPER_HOME $GROUPER_BASE/api
ENV GROUPER_UI_HOME $GROUPER_BASE/ui
ENV GROUPER_WS_HOME $GROUPER_BASE/ws
ENV PATH $GROUPER_HOME/bin:$PATH

# Web application environment variables.
ENV WEBAPPS_HOME /usr/src/app

# Environment vairables for Bouncy Castle
ENV BCPROV_BASE http://bouncycastle.org/download
ENV BCPROV_JAR bcprov-jdk15on-156.jar

COPY install-utils.sh /tmp/install-utils.sh
COPY install-grouper-war-runner.sh /tmp/install-grouper-war-runner.sh
RUN /tmp/install-grouper-war-runner.sh \
    && rm /tmp/install-grouper-war-runner.sh /tmp/install-utils.sh

WORKDIR $WEBAPPS_HOME

EXPOSE 80
CMD ["gsh"]
