# -*-dockerfile-*-
FROM discoenv/war-runner
MAINTAINER Sarah Roberts <sarahr@cyverse.org>
ARG git_commit=unknown
LABEL org.iplantc.de.grouper.git-ref="$git_commit"

# Copy the configuration files to temporary locations.
COPY configs /tmp/configs

# Grouper environment variables.
ENV GROUPER_VERSION 2.3.0
ENV GROUPER_BASE_URL http://software.internet2.edu/grouper/release/$GROUPER_VERSION
ENV GROUPER_API_TGZ grouper.apiBinary-$GROUPER_VERSION.tar.gz
ENV GROUPER_UI_TGZ grouper.ui-$GROUPER_VERSION.tar.gz
ENV GROUPER_WS_TGZ grouper.ws-$GROUPER_VERSION.tar.gz
ENV GROUPER_INS_JAR grouperInstaller.jar
ENV GROUPER_BASE /opt/grouper
ENV GROUPER_LOGS /var/log/grouper
ENV GROUPER_CONF /etc/grouper
ENV GROUPER_TEMP /tmp/grouper
ENV GROUPER_HOME $GROUPER_BASE/api
ENV GROUPER_UI_HOME $GROUPER_BASE/ui
ENV GROUPER_WS_HOME $GROUPER_BASE/ws
ENV PATH $GROUPER_HOME/bin:$PATH

# Web application environment variables.
ENV WEBAPPS_HOME /usr/src/app

# Environment vairables for Bouncy Castle
ENV BCPROV_BASE https://www.bouncycastle.org/download
ENV BCPROV_JAR bcprov-jdk15on-165.jar

COPY install-utils.sh /tmp/install-utils.sh
COPY install-grouper.sh /tmp/install-grouper.sh
RUN /tmp/install-grouper.sh \
    && rm /tmp/install-grouper.sh /tmp/install-utils.sh

RUN ln -s /usr/bin/java /usr/bin/grouper-ui \
    && ln -s /usr/bin/java /usr/bin/grouper-ws

COPY consul.hcl $WEBAPPS_HOME/consul.hcl
COPY templates $WEBAPPS_HOME/templates
COPY generate-configs.sh /usr/bin/generate-configs.sh
COPY run-grouper-loader.sh /usr/bin/run-grouper-loader.sh
COPY run-grouper-ui.sh /usr/bin/run-grouper-ui.sh
COPy run-grouper-ws.sh /usr/bin/run-grouper-ws.sh

WORKDIR $WEBAPPS_HOME

EXPOSE 80
CMD ["gsh"]
