node('docker') {
    git url: "https://github.com/cyverse-de/dockerfiles"
    dir('unittest-dedb') {
        stage('Build & push image') {
            ./create-image.sh
            withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'jenkins-docker-credentials', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME']]) {
                sh """docker login -u \"\$DOCKER_USERNAME\" -p \"\$DOCKER_PASSWORD\" && \\
                      docker push discoenv/unittest-dedb:dev && \\
                      docker logout"""
            }
        }
    }
}
