apiVersion: skaffold/v1
kind: Config
metadata:
  name: app-exposer
build:
    artifacts:
    - image: discoenv/unittest-dedb
      sync:
        manual:
          - src: database.tar.gz
            dest: /
          
          - src: metadata-db.tar.gz
            dest: /
          
          - src: notification-db.tar.gz
            dest: /
          
          - src: permissions-db.tar.gz
            dest: /

      custom:
        buildCommand: ./create-image.sh -R -G
        dependencies:
          paths:
          - create-image.sh
          - Dockerfile
          - setup-dev-database.sh
          - setup-grouper-database.sh
          - setup-pg-hbaconf.sh
          - update-dev-database.sh
          - wait-for-port.sh
          - facepalm-standalone.jar
deploy:
  kubectl:
    manifests:
    - k8s/unittest-dedb.yaml
