apiVersion: apps/v1
kind: Deployment
metadata:
  name: unittest-dedb
spec:
  replicas: 1
  selector:
    matchLabels:
      de-app: unittest-dedb
  template:
    metadata:
      labels:
        de-app: unittest-dedb
        app: de
    spec:
      restartPolicy: Always
      containers:
      - name: unittest-dedb
        image: discoenv/unittest-dedb
        ports:
          - name: listen-port
            containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: unittest-dedb
spec:
  selector:
    de-app: unittest-dedb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: listen-port