# Builds off of a known good version of the openresty centos image.
FROM openresty/openresty@sha256:59f5c68f3965d7fe031ae4182007d08a0c084b98fecbe06f13c4ada6561566de

LABEL maintainer "John Wregglesworth <wregglej@cyverse.org>"
